version: "3"

services:
  backend:
    build: 
      context: ./Backend/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3333:3333"
    networks: 
      - "interact"
    volumes:
      - ./Backend/:/usr/app/
    depends_on: 
      - mysql
    environment: 
      - MYSQL_HOST=backend_interact
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=interactclub
    container_name: backend_interact
  frontend:
    build: 
      context: ./Frontend/
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3002:3002"
    networks: 
      - "interact"
    volumes:
      - ./Frontend/:/usr/app/
      - /usr/app/node_modules/
    depends_on: 
      - backend
    environment: 
      - MYSQL_HOST=frontend_interact
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=interactclub
    container_name: frontend_interact

  mysql:
    image: mysql
    networks: 
      - "interact"
    environment: 
      - MYSQL_ROOT_PASSWORD=eduardo123
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=interactclub
    container_name: mysql
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    user: postgres
    networks:
      - "interact"
    environment: 
      - POSTGRES_ROOT_PASSWORD=eduardo123
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eduardo123
      - POSTGRES_DB=interactclub
    container_name: postgres
    volumes:
      - .:/var/lib/postgres/data
    ports:
      - "5432:5432"

networks:
  interact:
    external: true