version: "3"

services:
  app:
    build: .
    command: npm start
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
    depends_on: 
      - mysql
    environment: 
      - MYSQL_HOST=backend_interact
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=interactclub
    container_name: backend_interact
  mysql:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=eduardo123
      - MYSQL_USER=edu
      - MYSQL_PASS=eduardo123
      - MYSQL_DB=interactclub
    container_name: mysql
    ports:
      - "3306:3306"